### ISSUE TITLE
Using mono compiler on windows?

### ISSUE THREAD

**Issue by cambiata** [HaxeFoundation/hxcs#18]
On windows, it seems that the installed VisualStudio compilers "override" the mono ones as default. It would be cool to be able to set the default compiler to Mono also on windows..!

**Comment by waneck** [comment]
PR welcome ;)

**Comment by cambiata** [comment]
Ok, I'll give it a shot.
That would be a -D flag, wouldn't it? Something like
-D win-compiler=mono
?

**Comment by waneck** [comment]
Maybe we should do it like this:

* Check for VCS compiler on PATH
* Check for Mono compiler on PATH
* Check for VCS on the normally installed directory (like we do now)

We could also add an environment variable / flag to make mono have priority. A flag is ok to add, but I guess this deserves also an environment variable, since it might be configured differently for each machine

**Comment by cambiata** [comment]
Ah, just discovered the ```-D csharp-compiler``` flag..!

This works perfectly fine: Setting 
```-D csharp-compiler=C:\Program Files (x86)\Mono\bin\mcs```
does exactly what I was after...

No need to add anything else from my point of view. 
(Except for documentation... :-)
Closing this item.
