### ISSUE TITLE
Properly transpile constraints into C# code?

### ISSUE THREAD

**Issue by Kyliathy** [HaxeFoundation/hxcs#37]
Hey :). I'm a new and ardent fan of Haxe, although a bit rusty when it comes to coding since I'm coming after a ~4 years break. 

I'm working on a game logic engine. In an ideal world, I'd like to be able to write it entirely in Haxe and developers can integrate it into their target languages by directly including Haxe generated code. In order for this to be as smooth as possible, it is of course desirable that the Haxe output uses as many of the features of the target language as possible and that the code is as clean as possible.

That being said...

C# also supports constraints:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/where-generic-type-constraint

Do you think it would be possible to have this feature of the C# language used in the intermediary Haxe C# output?

Note: from what I know so far, Haxe also supports constraints for functions, whereas C# support stops at the new() function. I am aware that in such case it would probably be hard to transpile Haxe to C#, but perhaps an interface could be generated to satisfy the function constraints?

**Comment by nadako** [comment]
Some work has been done for that in https://github.com/HaxeFoundation/haxe/issues/3526, but yeah, it's a tricky topic. It's one of these topics where I'm not sure it's worth trying to satisfy C# compiler instead of "just" generating lower-level IL bytecode.

Anyway, this repo is for the support library, everything concerning actual code generation goes into Haxe repo.

**Comment by Kyliathy** [comment]
Thank you!
